from tkinter import *
def avg():
    k1=int(m1.get())
    k2=int(m2.get())
    k3=int(m3.get())
    aver=(k1+k2+k3)/3
    show=Label(f,"Average is: ",aver,fg=green)
    show.place(x=50,y=150)
def total():
    k1=int(m1.get())
    k2=int(m2.get())
    k3=int(m3.get())
    total=k1+k2+k3
    show=Label(f,"Total is: ",total,fg=green)
    show.place(x=50,y=150)
root=Tk()
f=Frame(root,height=350,width=350)
label1=Label(f,text="Marks 1: ")
label1.pack('left')
m1=Entry(f,width=10)
m1.pack(side='left')
label2=Label(f,text="Marks 2: ")
label2.pack('left')
m2=Entry(f,width=10)
m2.pack(side='left')
label3=Label(f,text="Marks 3: ")
label3.pack('left')
m3=Entry(f,width=10)
m3.pack(side='left')
avgbutton=Button(f,text="Average",command=avg)
avgbutton.pack(side='right')
totbutton=Button(f,text="Total",command=total)
totbutton.pack(side='left')
f.pack()
root.mainloop()